version: "3"
services:
  springboot-app:
    container_name: spring-app
    image: springboot-app
    build: .
    ports:
      - 8080:8080

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: dbemploye
      MYSQL_ROOT_PASSWORD: root